[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "9a08223823e2be9500cf8e4476434bc4509d4d94"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "db02d4120c4afb7d022e6e9600ad4d47a54b0503c3d9225f64174e35ccfd257b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "95cb15bbf34b13db8aacacddd0dcaafcbc00c897"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "f2a6dc873045074a0dc994f614da092aff295342a2bda44394025cef97efd50d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "271b655b139df82bcea4e73382656e2d20117502"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "6fd6d036283cd1eac8b93f659e9373a50f748654729e7fe1e44f114397a8635a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "e117b7c94579e448fa67c894d7f43972a45f32ed"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a5a01507b0ec8142c27d81c2819e90de69f7d77e1060138adbc2a07a8f15e670"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "d02f91464df57dab17827efe5d3cf46f7020215c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "93724f9ba67bcd51f8336838e7b9cf09788d1c4136be0d8fbaaf26a77b444b10"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "175b81637751f975304955b32302a7430e2ff506"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f75a47de2af93dd9c3059f546b62091e506da4f1a740cc1ec0cf33bb4c4d2a8b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "c42c8f7ee47f829b3fd2cedb8691974fa27a62de"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c53b5ad26571e5418facb4ef69515fb555553567480bda785264f8a2a510b08a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "aa1e36e8824b2448a8d12bd6721820f0c7a5f2a0"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "a58ba6a02007b3a38627a38edd4dcc0b314fba51e071db5e2604b1ae805ed492"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "daec8692d9a8300210130b572b19bad878be18a4"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "86a40871919f1dfbf0211a4c28860aad6cd6a621f1cd0507ba9cb6b6ff815140"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c9d9238384ca234d2370157b71d4152ed363c02e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "097a24060f0fac38027adae49d9e438fc8122ffb0f54690829b7c19519e65033"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "229a93da39d6e231dd73b477109946e724c79408"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d4d00f5343599c3fdaa926e6d8452c4de482995f8c489a225786117b53e44f98"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2c5c96fbe97e4be3aa397ce30716b4f849f5bcf0"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "594c47d7cacfdd4be75f72dbf624bd2c69e7577821a411940d05ec97ca92e5d2"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd33829de87c798a219ad903f1241232b7215c69"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "dd10a74560c79e995f553674a0966e2c278d6a4206a0fdc723135a2db2731bd9"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f78b958155091ae37bad453a2864233cf70b8899"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d3beed28e4f0f2584039d62a3537df3b3cad9d893c665af962830e039d2d3b85"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "254f76a0e12cb5ac696493fee26926f219302545"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d45b424f25bc0b0c45fadc5b1c579f2773109a5edbcad7fcdf3dae01f2f24941"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.i686-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "fe31fc9eb688a2a256229b093fce8c6bdb788f8f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "69de23dfaae160ad98590f61a8241e32eb7b0f9d67f001818aa490bc900dd1f8"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "80db4ef81bc3d0e44b6b5c55f9b086cbf9c47ca4"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "e852fcf429d90335062a8611438029a890a9e99220d5619d68a903edd250fb17"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "8e92e735035003a9df89fb7f1cb4c1b335f713fc"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "3cfd5f8ca17576c880360c67c3014a230048bbdce53b50180cdbb28d7afc8b87"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "6cb7a8c06ea80151dcab4334ac0bbf3833296738"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "11eea97de9c7950c0e343daa88764dc37e9e4ba898049b34819094b12b003d78"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "c1068198d32d551dac692621514275710dc78e98"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "0cdac0236e5f6046f133c1191588466849f4040249a4bdbe8264dc43358d2039"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "6cef813beac74ae12432384a685daf2664674105"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "5495b6086b730ac8a009ff660efeaa80ca8f2dab8ea0d872da42288ed63bc6ee"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "539ef28a486c5840593a7625618d544484926535"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "ff329b8d36df6f8cff78fe6dc4915b5e9dc2ee43bbab45fd70708c5bc96b2146"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "8216799ece3fa8495d6bcaf2994022fc9a7b1bbf"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "5dc6647a42156a4adb6b62ab7c8b5b323ca7a88db6e51c197e7479f214ffc5dc"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "6c67399d5ea1a0bd3f0b3b2aa58fa32c912da510"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "635473c7e815bd4d0d45b3b3f7e804e7ed976178a82655ff8e699f2f2c46bc36"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "2b2fc71ad2df9221a48d45b915f8ab6a6923b12e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "70fd7d8057b064be9d2101beebd9f5b4d99ef1945ee35cf72d04da61b4f460a7"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "7541f4567a8c4dea6c103a2b948e73c7e8966a62"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "3967260de9c5b60f755c41b64bda458b5fff22f8ce41909b836af0ec0fea58be"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "b9096d3c5fc6f9bd587d35b59ace83ddbaf98086"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "129da5210d99492fbc9d1079c08287b72dfefdc563380d6ac067555dcc3f73aa"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "ec0a1f6eb4586480ea684d7bace8411101db45cb"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "138b1c97378e4409b0912aa922cbe1c14d4608ecbc111e000c31b25057da57f6"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "8fec2ec19a52a820b35f2058f0cc8bd1b37c5867"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "8159883dda668af1338df80b38ae7f3ac5521237c007701313f2079753ce91a5"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "b070a42d1e29e422cc451fa56410c5eeb9800f16"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "2b920ed657bb9b7bfae1d461f2873926c4311e3b1505f933590ebdcc42ae18de"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "e7b6dbb7d16acc4ee9e846c4d1148d2512a23654"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "64b8447768f114bf2bae8145f74fde8bbce0308065d76d8d50130e0a097e2403"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "1c3fd73dcd7de1a6a0fa863857b0029de0986cfb"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "4e75ddadb3c6e93fccc8929d9b0ac7d9bb75324e0eb63031d8d53d089cc16ed7"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v2.2.1+0/LaMEM.v2.2.1.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
