[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "81f1741d51b629bcee0768c75574b19aa261d999"
libgfortran_version = "5.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "3fb4ae888e4220a187a005cb324e8bb1a4455f124f3652783f32d1aa159fafbc"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "6c3b7b864fd3153a123c731749b9d43507d81ae6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "21d60b7287f422543907f9cfc93a92cf3ad740e9d19be64ac9b03eb00548cf8e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "1c06ffd5981b2bf69ce854b76e07095976a5d76b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "5d07014de224aee638443a83d5f897feeedcc14c93135b8cddd6a2424293d016"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "c8eaa0c0561f00dda47b552baa34ea53b7befdb6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "11b60c6ce3aef8cb46d70e9647975edf3801403232e947494d5cd086a831eecb"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "b7ed158358d609bcb4df49df90343cff139deda6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "74e07b1f61488831504041af924e4a748c87a48823baef4d76fc2561167ec5d9"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "94d1c5e50684821b928f757faa449fecb2344237"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "6f63bcd68b48460b01d623985ac27ec6242d80fb4914524d3b4512c58cbdd08a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "75f1a94190c5233f4dae88add98ecf0737a1f538"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f1783d63ec4742c60c76366acd886447aaafc37ec01139d3790aaac13ab037cf"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5646de8b387d9fccdfbc96878d97376fa71be81d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f5ecad7ab6cfe22eaa7831690c7ea0e2ee247370c2dceca090c57125a5fac0a8"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f2732867501d2acd8b880973fb69a0b3087ae66f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "34373224eae0174f0ac9908728e9241e563d7d1b87ed3303c57e06ad5f584dae"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a5fe021430446579c6890064494125054e083b8e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "7842ec0c986a0ed950cd92a0361478bed71d75d1f9276f12af32a19269e1bd3d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9096372578a9a647fc46d205f23d7d50051d6d7e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c4b40aa1d90f545a7cd43d11c200bcc5769c0cd42e72fea297c4a8d4e79807b7"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1315742ebc0f556e02f7e160c121502d4650617b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "194a99cce9fd2f02b213bac4b7566133f7f451223a69550267e4609360ae1b1b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "064abc48960089c785472da794e56247442538a8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "e85bc66e349b6bfbc44439eb62a9934d1e1023764f7fa9f5cce34705fa43cd50"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53ed724d116437a1225aecf57137a0af4b8c8d61"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "fba34960ba31617bbd45c7dc98f81f54f4e76e1231299aff1aa1d84041cda6aa"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8fa881402238b55f3c8b4ef93975fa6fc5defb4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "1782e34402ba45647869ba79ec908a09d96ec70c2b9c829ed44b84fb3a7f22d6"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b4abb6326b21cb800b354babfd79ede63be413f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "ed612bde838066a78358e3f1a45275976dbcfc84641795e5c9fb6f4262a9d498"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f432a2536d0d84778b90bf59b63fed5cf03c2cb6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "334b68995472017e834d4f40546119d031a231e25c1ebfb46f37f890a0259ff9"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "987e1bef86df54dfc012810d734c823d8cc9e451"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "5c11e74308021191910262737b0e1f86ce2b0ec72254f7f2e7f4fa3f1de0d28c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "89eb689be949b0661d8895deb51038574715a24a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "a2bf3cb3091994a5554ec38f0f7bf6f478ca5e2963e7472a0249cc03799d59a3"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "55e6f1c698dc2723e4a9f5a1f5c40ced084ea1af"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "b51aeab832fac492c573fc5bb4b09929d09818ec1dc57e1ef8e2140fbc6459fb"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "951d9a5b7ed77d033b1d9dae1a6b0b52280fea1c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "590c74265ebaafc510edfc40b2007f9807198832af7c97e7760390574e59e780"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "c80a7e0451beea6b21484301bcb8fb01e272a7c1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "7237d53c0aab4397f5afdd0f7cbbe5a58e44db6e5d90abb51d17658755d0d8c1"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "a61c00bbddddb3742a8d3b85215abc6f35563762"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "09fa0feeaa560e43a5f52468f2a2f9ada7f5897c1f962413a4334302f3693b9e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "371c57673ccf2614e1b709dd85e58ac87e301609"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "7ca7ed674eca918f8ade33ceee59c957fc6136232defbca5af8ed9860488f1b2"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "dd2fbafaf451636acf46f60133b64ac1c34192cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "dcedd0d5a1ea5501381c9d2330e3d3bda967da93bbbc6e7502a96c73a2b9236c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "d94ee76c7f6ca7d80f8106c56f4b39fbf9fa770e"
libgfortran_version = "3.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "c1fcbec5c58d5624921be169b5bf7a11a078a3956f057e1eb830c01fc8a8a000"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "b7579f2ef7e3e686f4e0eb663ff47604064fb30e"
libgfortran_version = "4.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "78f192e2fa417c5c0f2b197484a3facd2eb5505a050050fdcc4dcf468b2b4b44"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "7c777c89ee0d1b03406f5418e58522eedbcd5edc"
libgfortran_version = "5.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "6251a5872f8e03d4d92d4aac606a5f56c5115f9ad99d3cd3be0a4331d885651e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "f5de330b844da5ec0b0de3b323b61568a26207d5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "08273e06b91a3b3089965c83b3964409b03da5934f93b1a37c385faf056ff5bb"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "51d156cf221411ebad778ddf6aaf64cf62cf2130"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f8831e16f4f18a8a4779b9bdb6b3c02f7871448db8a6aec3bed98ae4f2316b05"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "6270e7dd5f8fde9d7ec4c4fd5093ff3fc1e2d2cb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "5114a14732b91c71dac94a564cb50420c6159cb5cc2f3b4208a22c33d2f12725"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "fde2bf52fae22b05ec17a24f8b1a78d4587aefbd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "bab65d7ad7c2c4fabe70985b778758313fc209f43854ca94eb81e9c7de7de377"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "fbc0946dc06fa839c417dbacbdbbac6fb548d4b4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "99462f69ca6735f93d8772cf6950b2f442c0f584de6996cefff406def887c711"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "ca77fa94c97214b3b7b2cbbac341ea917a0583ac"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "78ff57b529732bca8075a5e38309a4a9f1dd197110964438e7e1bfdeec9dd9a8"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "7fb12d0c28757c9c78ed0330b1f681d730f07147"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[LaMEM.download]]
    sha256 = "0dc32b25131a93ea0c9f9bff8cae3f5b4aa763f323f4b600f03f9a33b62eb3fa"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "17abed2376a6b394e83fc37e7cdc254ab0063e3d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[LaMEM.download]]
    sha256 = "cbed7edfe94f735871c0508728a972de16a6edaf0edcba19f8400125661bba7a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "6e0a6450dd45710ecb50b7664ca6f021ecfe344f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[LaMEM.download]]
    sha256 = "6fd9ce6a4e5e25cefd77cbabcf756c8220725611e50f34ffd987642ab9ab11ad"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "768af993d509ea6a24239f3777e77a45f1325614"
libgfortran_version = "3.0.0"
os = "windows"

    [[LaMEM.download]]
    sha256 = "24aad160e3edffcb33b4b0cb32c8a6504d8882cc469152e5e292a820ace1795d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "ac61cca6a2ba328ecf057cffb216f9f1132f41c8"
libgfortran_version = "4.0.0"
os = "windows"

    [[LaMEM.download]]
    sha256 = "16422af34bf740211dadd25099f6238ea4dbb725666126348310b870dca2232b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "8a20a06a4bd0a047efd96156081af17e91aa6254"
libgfortran_version = "5.0.0"
os = "windows"

    [[LaMEM.download]]
    sha256 = "155836b23fab9efe7b18e55fcb1fc92fd434120750a1524101f6f1ec3157279d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+2/LaMEM.v1.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
