[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "08d189d0c3a96996d63f4a0d00c8eb3b029fc498"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "13b7c8b0d8ca5ce89dd741e96e45582f62a1a09dd61d86742e49bbc496aa0a7d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "1397dcb53ea638f1fddbdf70655ca5f4ebc31103"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "c5f25deb844e12350b4d5f1bcaab8215d96a6ab5c74192856fedc48461fe1a85"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "a99d1614926e0d2d480ac464a75b823e061afc09"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "91f37ab56f52f329160e1302296392830f25931fce15a9ffc2ccfe3680ac44f2"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "646b61d52e89e818636d32017df2a900409b1321"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "4e1b573ff3f9865b488c627a811deb1ee99062a466c73bfebc891cb9f2d5df06"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "8cad2e0b160c2f756edee3edfb2529177bd9dddc"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "efa7918bcbbdb71d455cb37df8c7313ebf7e77916e76196ec30f95f28c0cc5d1"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "6d33e7e57418ab5f82e1c1970d4f7a3bf4e1e535"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "2d4a7f1cb415de4c30a628d9a362b90d81b46c097460b81c6a6260364e10a8be"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "0de00140bddf8bbfe5b0b7fcdc7cc65479d1350e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "4ede69294d89bc2d5a5c6e9de74aa126e06a59326790bead9b86bbfd490cfc61"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "107ec50d47f297460392941e4f8900b28e07ad76"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "4aaab93b1622266731cce53c6432f56dcc70d9f9d6b3234e3a21d0d8688618d5"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "3108fe7b7ecba64e19aeec9ff248b9cf2b267276"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "87b038f26422d1422f8513793388ae6ec479c251a17c541483cb2ab4cacf3e01"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "2dc79bce79211305bcee6fc34c87668a9738ccab"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "333a6a277bd6cd29a7f3bae23a7b146e5d20f28c4d27043dde809de35d8ce122"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "039f8a2588e6f855f061ce167f56ff06f2f7d082"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "ae2c5cb1601a821e4fd55c9fbc69aa05731228bb6003e69f563f01e658c21224"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "c93de6434ef95ee5c8a0c9e62c8b390fbb2fbff4"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "0104eedeb1e3d4c8aea79587fe6d53f79adedff920f76b1fec080a68b2601d33"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "5a0761c9fc9a0e048de76dfe950c97ccec3c3d07"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "b835431a3e0e71f2e00358e045215a0af4f5b66b84e116ccd1c93d27d2991a8e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "5c3d546248b4468423fb1b5f7c990905a268119d"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a72dde02b40aaa0ed0d3ee402c94dd3ec86aa3bd68801bcd738abfa5ccd13126"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "5b878264400310cedb33f4520fd501f43e293f1e"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "ce30239b3ef194ff5c45cbea92dcc39a50b4ac7a6768c659bd7250a081c191c6"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "3ae00a43c09915796bcd894719e1016fe7bf47b3"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "ccebab1d392d1f5bd16e1644b4358625bfd734f29a421e9132261cef3fa0134a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "4e42b69e9fa9bb1deb8fb4001cb5fa6fad1138c4"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f89d68c7acfb21c455247c50f687955f6701e35f4c6bda3797920b9f5fae3254"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "37420f2dc37cc25d4108e80966e6e989de0a9b55"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "a4f298db5aa05f94bfd5cde7cad8cdc07b08869595e69ca0723de14245a6813e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "06911291d51405359124f3e54df00380badc7ffd"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "20a4e9e9e2be1478a695a7bfbccb2e240d461bb6eb68a7fcab05acc08ac3bc5a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "99eed841c86c5a25c004b02a159dfa62f4d199fd"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "69b4291869da1e62bfeb6718dce89f76f05cb66a34a8c30bd503f1faaa803d9d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "452022d1f8901a020d3751cc911f4e30215961ee"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "50c908ee5a5c68217ecea9f3cb2c93440fce3664ac6cc3fe34cf158b52e9cfe9"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "7a2e3df6075f8f75463b529133efc3d2b0831d4c"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "0a252e7b9d254fb20a4471596c509cb1e04f266718f8ce5021772cfa8f974127"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "3f1aae99b4ef57f26c6b35a85ecd1fcbe55425cb"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "90d65357c4a7ae26643d82901f387a33b77ac3fa772546ab74ee25879e46e14c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.1.0+0/LaMEM.v3.1.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
