[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "3783b812fb92cbb11e81d47801b885729af9e106"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "fef3e16a360d3daca310ad4b91ad4cd82256927d24a1ee7047498d9683194fce"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "8074f67c34b8cbc6ac8a75de28dc814bcff75d56"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "0c6a7518b288c8e6e8d7bcbaeefb6c0d51235a78a8ad865a314b65986f37e0ea"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "6414d0395248a64ea5472e5aaa82b1b128241aed"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "d7eeebe4ea1ed76f8544bf1ce4b8faad53fdc2e5c807043a53a08261a920d229"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "6a79aaf6e551698005d0dfd021d16865bdafb45c"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "dcabc22aa297aa8404f4c91d7b03bc37891a173a54884537cea9b121c434d03c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "d800ae2571ce385911dd45c6365648dd8cbf512c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "ce39025041b107e4715f9d1fd22ae16c7afe765786a60abf90d7600a402a26fd"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "4cf75c28b969cc84bf239ddc0fba7edfda8d2662"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "7c06426cf72845cb1bdc98a09b6c9ad7d5a32b5a304ecbc32043cdfcfba10c52"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "a3ae6054a299699b7f02573556ad8a3c99061751"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "83c644e5941b894ce311e654e47bfc050cdee86a3321c04e374bd03cce9f386e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "ebe1fbf1fe43dc70ce3953dd828d27a68efd71c2"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c48e091b929f07dc77fa7e9ba1a5c67e46d2f1bee4a5089caf78fcc3018c5da2"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "34684efc65df067405b4be5ebd613fdfd82e8733"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "eac147c296bd7eb1a73318246c64dc760066f17c190f61d872790e0f29537cfd"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "767cf049d7dc2962a6bc59c89f06831f724fa138"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "5608f23cf9271254fb40faada1ada2966e6aa864935a0ffe763659af7c60cac0"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "455197aa5f2504e3c54057f0bbdf814155cae4a6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "74f2c007378f513258a7e13c9cab9634df0f246305542f8a6399427b838f2803"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d7ee702d2bf5997aacae77df5e380891b61a0b39"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "4c67c315b67419ea8eb96d2ff51a65e142622be7d6a4603027b2f3e6713d73b5"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55db3954c9b52f4f0037c0068422899e8d210f93"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "57701eeff1000af0eac945df204c4cb9999386eecfc63c6802fd69ac03d4e4c4"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ea206baa02ff9eb6bbefc4bce8f32113df2e124"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "359e9fa72d6e9026e3dceacaa0c753ae86c7557caa5bec14d6fa384e27208a6a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "01d8842a3acc1eba5421eba9bf820af1971cc5fd"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "64fb34387820c682f3793e1a038fa06145072e25beb6e74c6dda98c8bf90b32e"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.i686-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "1df36aad2b669e46e6a3f66e9ee6f40e0fbd87e5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "51c4543366efb1d1d0fb8739f5806a4df5d0c222f6d153d145090bcb8e648da9"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.i686-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "0a78298ecd75b864ad15ad6edb186dbb549879ca"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "b35c207a2fd2265b182f5b8565cf30ab24795901a95a65ae881a5a8aafda8db2"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "543261383f6baea4753180b761a00e817da9468d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "9e0ffe4183d92d0245f48552a635f0d311ae8e9b4e3c16459584c79945cf9467"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "f76cb5e1f495a2f62aeb20b27a666874561ba5db"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "eb88c028684421235bb09ad85af9409d7e21883e547055df8f249706c7a27fbf"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "ac07bf80921b6756e5979b026dc4fd1d588edbce"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "da38ac9888739bf42261f95d83f36e43289c1051dfcc5d72f1a028bdcae70d6b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "3454356f5621882cdbdbd5bb2a2f5f9e8eb58eac"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "233ef6947520ae8a3877d0d3e0ba11813c57862e6350881c9975f1d76edd2ddb"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "93b0c60316be37bb27ceb98fe2d3e75e4eae6ce1"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "2903656e3c0f0967ae5246dff2b74b64e1105fef1aff2569658997146a80aca6"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "9d5376efee4842874e728f0fe41b266dbe28e643"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "bacebe19ee5bb86df2ed390225aa96b51fe84573ce6cecd9764af3dccafa6efb"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "dc079d7b29132595c183706254529cb994655e40"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "1c76759d48466f212d812d1a99ae31a90e371a044651a89ba3d2d49530c0d49f"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "fa8308c331a7f726dcf99e0cdbba64ffd1101b4b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[LaMEM.download]]
    sha256 = "38a42bd350f9d9264ffd3b21910419c91073f0e17e1c19d8ab7780aa8f94b66b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "70b5c6a9a801b1e38497f8376d469c043db1de25"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "60a6105815a49a8d588c671045eca8905c7f2c9af095e0820a82b5f9bbddbbc5"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "676a4d56aa4140964528d661f6823e6fce20a90e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "fd1b665e74948d950653d2aa3c88e81200946dcb7917adccc80ffca2afff34f4"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "58037e7cec19513e3d5329e8cb5be4759e968312"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[LaMEM.download]]
    sha256 = "2a93bcad48ae183c1d6dd9fda3f87cf4a6276cd12cae5b2d82d5a17a9ee78033"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "07868799e5bfc7c86d99b6865132c678137cbf91"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "65d9ab54fd80da4d02ecaf7ec24da58534531f2e19aafc1c877a0f7d98761900"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "fd0fde24682b066bb97494403d98297fc957cd24"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[LaMEM.download]]
    sha256 = "b62f2595f2b783d982f9afa331b8cd856f5bc5a372a180e62abe0e4697d8a8af"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "b762f600a8269fe8dbd50eeb1b6cdd5c93b453df"
lazy = true
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "a4283554d80a4349ce822fd487ef3fc2f02a26cfb053bb7ff42ec48030955c8a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "7134fce604b9e8775a6e28583d69c1c03836ba53"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "2d92ee9d89b10901609e457e5371df713f64437cd042b5dc8039e91bacd8f3fd"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v3.0.0+0/LaMEM.v3.0.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
