[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "f275c423f7917e7fb0d0ebc6f3305eea888f1f44"
libgfortran_version = "5.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "d3341332d18558d17cc583f235cea74decfe94af9f37ffb4b12c38c711beea66"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "3086598ee7bba5a8693ff43be7dcc6584f0ea4d3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "b32fdc91a264cec5f6549a6892aab9f50a7c236fa28b6c9fd9a2600f6531bcad"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "66d0f308c457592c6d6dbc3b8a6424b6788b4c21"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "cb1d36ecadf55000638815888613d9ab900f36bfa8f08916dadf81416f553d4c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "fba649478b8ce9655a8a997ea80069b48861b080"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "47dac275d2c857b8ab647f6dd4265975a56ddc2a7d8b60fe5936cf438ca2e126"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "0aa340e40fa5d2823f9ddf5e57d93f8c3f50e0b3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "94a98eec0a3981a4bcead7f5526fcfc3ee5a121a79c81c01eca588ad7c25aadb"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "6e3901d594652c63d44d8c0182d3ac9a453d8e37"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "49003eb1d98db886dd87aed1977fa61d0634f97deaf4437ad820a7dc77530253"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "7adcbb5795e48cf771d2835107ec5fc115ee8262"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d30c27141a8fe9cffa28073954eb4dc9d6197da16759865cea0bc7c69860c886"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "265c4c5471912e275f566b196b2e97753d027706"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d4cb739f1e64a7244ecba0dfd90937a33943ae179adc1b5473b64f0b298f1b45"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7f68e9d279a3ea8435626a050680a0de18030699"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "71ce02460241af1c99a56be8939326c3d47f43bb444ffeb6fe6b2460c210ef3c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "abbb8a331b2cb7cd457de28d631dc6098f954815"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "04edcae3221fdac0138a92e744be589f4600e48a75949adbd8d5f06a4623802a"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "45ac5c6cf501df80ef08137b5b862050263f1cf5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "e7d41d46243d7d2f4038f78a39e583b5732a61ed5b11c192ab5a23cda415b9b5"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ab14603fabd329e157b8f00a3cdc8a0949ea5c5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "b6920941188200eee8891f32be6510f43c3547b85c51c9bc125e85105ae5d6a1"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb9639073f0efc5d873660f5cd5da22f08949534"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f0c985e5762e44ff86fdd14692360ba28fa58483b68fd1e6beda340a6fdb434d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "15895bd5ce765dc5c25662af99f703f4523eaac3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "adef9bd88664505a124f1986dd38fab451025c33f556f603eeb9052c7b9f1e62"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b04b2a0234bcec4d28a5a5869d1e0c6641c369f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "b48bd2b245264e3e87477d7cf9f31f418ab0177bc347f7466784e6571d66be1d"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56d33fb40582b845debe9a2651bcd0745d1a9587"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "1cf7ad9aaab2673b2e52bcfe44816cdbdb2203c647a530b722c30cb0fa9681d0"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8bde6216a91bdf63666bc4c4130d7d28624d748"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "46b2837081afb42541dd00471cc252f7ce5d6c885acf12aec61fd45476b68275"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50d09ea3257107f9b034d7a518491f9403366ecd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "ff003376dd0a192ac9c1e8b55f82e835db63cbc414d5a11ecd3d9ea8e1274533"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[LaMEM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fba59c118ce9a41c64190c3279878bb470920fbf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "38ab6637f118d2a997a9aed4b1e9a56589aa89b27d73180ea8b49680d1b9c0dd"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "331bad74a20601587a7717ea7c8b95330a44f414"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "eeb2c8383ef218881bf4bdb38bfe680e83e4c735f48f2ebce7d44887e82efdc1"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "2563ac316610a3cab925d703cb6bbf88c73d77b2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "760617a21a1796ec7f4d98c474dea5a5664478cda7b1f507ed59daee1994d3ae"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "i686"
git-tree-sha1 = "1f824941d37f5349d72a8d63ee038a335206f7ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "2a570cce2c4e1ddca0ce21d2d07eafe3b25e9a66364f2b87bb7a99188339568b"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "b17b961275639177d0b31840824586777f479f9f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d3597f46b3fd2d033a5bc9a44783ad0fac1e7493aedc9fd89fcd055032ba45a3"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "1d9ee55f40f139e61a2335e3690f564609c9d155"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f22612adcc668606129dcde0a58763b7f172f2880f98b1cf348810b5bca7547c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "powerpc64le"
git-tree-sha1 = "a6644305404f78e49d9c2a887f5b3ce2223dd8d0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "e52b72597ee751019fd78d8ad63641ecdf6e5b77cb45cac0df98b5469b8b6bd8"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "b3ca83780d7b7cf4b69f4c2481bf2055454a1165"
libgfortran_version = "3.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "6f41350a690983c46081494df0f3c6f1c85ad86e55b97369456050b56e1fb652"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "ace8f15b979ba7011c191b5ba287dae3d2e1e457"
libgfortran_version = "4.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "45700538a8c25f3caf159b725ef781630667def5172e49a937beaee8303f9867"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "8c81e503eb96a54cfbdf375f2bd6d0c14533b4d5"
libgfortran_version = "5.0.0"
os = "macos"

    [[LaMEM.download]]
    sha256 = "96555ec3539f7c89968991fae18b4278ed3029df0c0283f5f8f0f2ee681766c9"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "eb39a861606de75d44668eb9c98444dac4d202e8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "06b380ce3eef78b1d652a234be874a13253f229a8716587360851f0d8f33055c"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "d443088f8ba5de3ded6a39383691d2a4f536cc5a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "0b77bd0665006be0e49eee439cfcabecbb9b10e3366a3b0699a2af5dbeec927f"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "2115203323925fafd8e4a1371647fbc2c14839b7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "0677520a02fd917df271a07c5c6039faa249417cf00b980207e742cdf35e4718"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "e2e11c24f134c449c84326dec81bf1ed48b9ca8f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "ff05b403b8dd98a71a7cc2031b9513be6b1f27eed2d54ca1a460f58b9ec23bdd"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "e0867a00912a5c1292a40e101c8de43bfef98bf1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "19eef45d5168665ce73c6dea685aa9e88ffb13c8583bcc352b22a75ff6aa1198"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "8be0f5dad509bab3eb4a4ded54c82f198949d01f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[LaMEM.download]]
    sha256 = "d91578d992e84cf31ad0be9dd587fe40f89773dc052418555762935b22330530"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "a69f6b0003735d031e28bf4057bcf6a7b35b83bd"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[LaMEM.download]]
    sha256 = "6440e72583b22dafebc07edcb9cca1e17c166bca232543a93aff90d40c07f1d1"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "8c2e87c71396ba78f7d30198b8966e58415fc23d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[LaMEM.download]]
    sha256 = "f2cdd0345b6ac8d25df546da5d5eeb8d99520e32480961e3c39b0c4a4e354118"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "c447367c50de8dff7ea97966f55e9f8b653ebf55"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[LaMEM.download]]
    sha256 = "3aab6e9f9378cb5724003aa679efd96c3f8f1f744f6ce07fa50e6c42a050ddbc"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "6e9005b23a8a38d056eebf031ff8d4993c459dca"
libgfortran_version = "3.0.0"
os = "windows"

    [[LaMEM.download]]
    sha256 = "d9ca214d4105836b85bb6beecf26df158f551426bb14eb26fc10b02dac9cd098"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "81cef4bd40b2f7810e2a7922559c831583063ccd"
libgfortran_version = "4.0.0"
os = "windows"

    [[LaMEM.download]]
    sha256 = "47cc82eda626bba8080b8feeabbef92a2e37ab0d0ec7c2e9d4179b10eb6dc483"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "2d762b257c2e229fd25d5793c997f82c9089e64a"
libgfortran_version = "5.0.0"
os = "windows"

    [[LaMEM.download]]
    sha256 = "ccc4a17b8e373f243fc560b5154906b635e45d67040dc293762f36edf9d61c93"
    url = "https://github.com/JuliaBinaryWrappers/LaMEM_jll.jl/releases/download/LaMEM-v1.1.0+1/LaMEM.v1.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
